Refactor for 0.1.1.1
haskell-jp/unicode-show pull request #9
Opened 2022-03-20 09:33 UTC by igrep

@ncaq 
まだCIがこけていますが、可能ならレビューをお願いしたいです。
主なコミットは 898cde9cd05f140b50b7c752682e1b87283f90ab で、 https://github.com/haskell-jp/unicode-show/pull/5#issuecomment-964117542 で触れたとおり、ダブルクォートの中だけrecoverすることでlexChar関数の挙動の違いによる問題を避けるよう修正しました。当初`ReadP`で実装したんですが、`ReadP`は可能性のあるパース結果を全部列挙するタイプのパーサーである故か、文字列の中にダブルクォートがいくつも挟まると実行が終わらない、という問題に出くわしたので`StateT`を使ってパーサーコンビネーターから書き直しました。
同コミットで依存関係を増やしましたが十分に軽いはず。

2022-03-20 09:35 UTC, igrep commented
CIのエラーはやっぱり `\&` の扱いか... はぁ、古いGHCサポートしたくねぇなぁ 😩

2022-03-20 11:32 UTC, igrep commented
くそう、なんかいろいろ不運にぶち当たって古いGHCが用意できなくてデバッグしづらい 😞 
https://twitter.com/igrep/status/1505487681220145155

2022-03-21 09:08 UTC, ncaq requested changes
`tail`の使用はやはり`put`で避けたほうが良いと思いますが、いかがでしょうか。
古いGHCをサポートしたいというのはもともと私の、hspecにねじ込みたかったというわがままによるものなので、hspec側がコピペで対応してしまったので、切ってしまっても良さそうな気もします。

2022-03-21 09:08 UTC, ncaq commented on src/Text/Show/Unicode.hs
> +            modify' tail
`tail` は部分関数ですが、安全は確保されているのでしょうか、確保されているにしろややこしいので、出来るなら避けるかラップするなどをした方が良いかと思います。

2022-03-21 09:08 UTC, ncaq commented on src/Text/Show/Unicode.hs
> +            modify' tail
ちゃんと読んだ所パターンマッチの性質上安全は確保されていますね。
しかし、パターンマッチしているのであれば、`modify'` するより `_insideLiteral` を `put` するとかの方が部分関数が除去されていて更に直感的な気がします。

2022-03-21 10:02 UTC, igrep commented
> 古いGHCをサポートしたいというのはもともと私の、hspecにねじ込みたかったというわがままによるものなので、hspec側がコピペで対応してしまったので、切ってしまっても良さそうな気もします。

正直なところその答えを待っていました！私もそう思うので切ります！多分`string "\\&")`の部分も削除できるのでもっと軽くできるはず。

2022-03-21 10:46 UTC, igrep commented
@ncaq 修正終わりました。ついでにGHC 9.0.2でもテストしています。このまま特にコメントなければ次のHaskell-jpもくもく会の時にマージしてリリースします。

2022-03-21 12:08 UTC, ncaq approved these changes

2022-03-27 05:47 UTC, merged

2022-03-27 05:50 UTC, igrep commented
リリースしました！レビューありがとうございました！
https://hackage.haskell.org/package/unicode-show